export const GET_USER ='GET_USER'
export const USER_TOKEN ='USER_TOKEN'
export const  USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL ='USER_LOGIN_FAIL'
export const USER_LOGOUT ='USER_LOGOUT'



